import * as React from 'react';
import Draggable from 'react-draggable';
import Head from 'next/head'

export default function Home(props) {
  const { stringToRender } = props;
  const [content, setContent] = React.useState(null);

  React.useEffect(() => {
    window.React = React;
    setContent(eval(stringToRender))
  }, [])

  return (
    <div>
      <Head>
        <title>I Can Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Draggable>
        <div>
          {content}
        </div>
      </Draggable>
    </div>
  )
}

export async function getServerSideProps() {
  const stringToRender = require('@babel/core').transform('<h1>a</h1>', {presets: ['@babel/preset-react']}).code;
  return {
    props: {
      stringToRender
    }
  }
}
